Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   :
// Autor(a)    : Eliziane de Oliveira de Paula
// Data atual  : 05/04/2022
Var
// Seção de Declarações das variáveis 
  Nome: Caractere
  


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Digite seu nome: ")
   Leia (Nome)
   Escreva (Nome , ", seja bem-vindo(a)!")

Fimalgoritmo