algoritmo "semnome"
var
A, B, C: Inteiro
inicio
      A <- 2
      B <- 3
      C <- 5
      Escreva(A=B)
      Escreva(A<>B)
      Escreva(A>B)
      Escreva(A>=2)
      Escreva(C=A+B)
      Escreva(C>=B^A)
      Escreva(1=C%2)
      Escreva(verdadeiro e falso)
      Escreva((A=B) ou (C>A))
// Ordem de Precedência: 1º aritméticos ()^*/+-
//2º relacionais todos
//3º Lógicos E, Ou, Não

fimalgoritmo